# Generated by Django 5.2 on 2025-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("black_invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionsistema",
            name="rif_empresa",
            field=models.CharField(
                default="J-40723051-4",
                help_text="Ejemplo: J-12345678-9",
                max_length=20,
                verbose_name="RIF de la Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionsistema",
            name="telefono_empresa",
            field=models.CharField(max_length=60, verbose_name="Teléfono"),
        ),
    ]
