# Generated by Django 5.2 on 2025-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0002_add_iva_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelacceso',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
