# Generated by Django 5.2 on 2025-09-09 22:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0002_alter_configuracionsistema_rif_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(help_text='Formato: V12345678, E12345678, J12345678 o G12345678', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener el formato V12345678, E12345678, J12345678 o G12345678', regex='^[VEJG]-?\\d{6,8}$')], verbose_name='Cédula/RIF'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='black_invoices.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='notaentrega',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_entrega', to='black_invoices.cliente', verbose_name='Cliente'),
        ),
    ]
