# Generated by Django 5.2 on 2025-09-09 22:25

from django.db import migrations, models


def migrar_datos_clientes(apps, schema_editor):
    """Migrar datos existentes de clientes al nuevo formato"""
    Cliente = apps.get_model('black_invoices', 'Cliente')
    
    for cliente in Cliente.objects.all():
        if cliente.cedula:
            # Extraer tipo y número del documento de la cédula existente
            cedula = cliente.cedula.upper().replace('-', '')
            if cedula and len(cedula) > 1:
                tipo = cedula[0] if cedula[0] in ['V', 'E', 'J', 'G'] else 'V'
                numero = cedula[1:]
                
                # Actualizar los nuevos campos
                cliente.tipo_documento = tipo
                cliente.numero_documento = numero
                
                # Crear nombre completo combinando nombre y apellido
                nombre_completo = f"{cliente.nombre} {cliente.apellido}".strip()
                if not nombre_completo:
                    nombre_completo = "Sin nombre"
                cliente.nombre_completo = nombre_completo
                
                cliente.save()


def revertir_migracion(apps, schema_editor):
    """Función para revertir la migración si es necesario"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0003_alter_cliente_cedula_alter_factura_cliente_and_more'),
    ]

    operations = [
        # 1. Agregar nuevos campos con valores temporales
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(
                max_length=1, 
                choices=[('V', 'V - Venezolano'), ('E', 'E - Extranjero'), ('J', 'J - Jurídico'), ('G', 'G - Gubernamental')],
                default='V',
                verbose_name="Tipo de Documento"
            ),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(
                max_length=9,
                default='12345678',
                verbose_name="Número de Documento",
                help_text="Solo números, entre 6 y 9 dígitos"
            ),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(
                max_length=100,
                default='Sin nombre',
                verbose_name="Nombre Completo"
            ),
        ),
        
        # 2. Migrar datos existentes
        migrations.RunPython(migrar_datos_clientes, revertir_migracion),
        
        # 3. Remover campos antiguos
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        
        # 4. Hacer que cedula no sea editable
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(
                max_length=12,
                unique=True,
                verbose_name="Cédula/RIF",
                editable=False
            ),
        ),
        
        # 5. Cambiar el ordering en Meta
        migrations.AlterModelOptions(
            name='cliente',
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo']
            },
        ),
    ]
