# Generated by Django 5.2 on 2025-09-09 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0004_auto_20250909_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(help_text='Solo números, entre 6 y 9 dígitos', max_length=9, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='black_invoices.factura', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='nota_entrega',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='black_invoices.notaentrega', verbose_name='Nota de Entrega'),
        ),
    ]
