# Generated by Django 5.2 on 2025-09-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0004_add_iva_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total_venta',
        ),
    ]
