# Generated by Django 5.2 on 2025-09-09 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0005_alter_cliente_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='black_invoices.factura', verbose_name='Factura'),
        ),
    ]
