# Generated by Django 5.2 on 2025-09-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0004_add_iva_system'),
        ('black_invoices', '0005_remove_factura_total_venta'),
    ]

    operations = [
    ]
