# Generated by Django 5.2 on 2025-09-10 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0007_auto_20250910_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nivel_acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='black_invoices.nivelacceso', verbose_name='Nivel de Acceso'),
        ),
    ]
