# Generated by Django 5.2 on 2025-09-10 05:20

from django.db import migrations


def agregar_nivel_secretaria(apps, schema_editor):
    """Agregar el nivel de acceso Secretaria si no existe"""
    NivelAcceso = apps.get_model('black_invoices', 'NivelAcceso')
    
    # Verificar si ya existe
    if not NivelAcceso.objects.filter(nombre='Secretaria').exists():
        NivelAcceso.objects.create(
            nombre='Secretaria',
            descripcion='Acceso a ventas, clientes, productos y reportes básicos'
        )


def revertir_nivel_secretaria(apps, schema_editor):
    """Eliminar el nivel de acceso Secretaria"""
    NivelAcceso = apps.get_model('black_invoices', 'NivelAcceso')
    NivelAcceso.objects.filter(nombre='Secretaria').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0008_alter_empleado_fecha_contratacion_and_more'),
    ]

    operations = [
        migrations.RunPython(agregar_nivel_secretaria, revertir_nivel_secretaria),
    ]
