# Generated by Django 5.2 on 2025-09-23 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_invoices', '0009_agregar_nivel_secretaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Modificación')),
                ('tipo_modificacion', models.CharField(choices=[('productos', 'Modificación de Productos'), ('cliente', 'Cambio de Cliente'), ('metodo_pago', 'Cambio de Método de Pago'), ('tipo_venta', 'Cambio de Tipo de Venta'), ('completa', 'Modificación Completa')], max_length=50, verbose_name='Tipo de Modificación')),
                ('descripcion', models.TextField(help_text='Descripción detallada de los cambios realizados', verbose_name='Descripción de Cambios')),
                ('datos_anteriores', models.JSONField(help_text='Estado de la venta antes de la modificación', verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(help_text='Estado de la venta después de la modificación', verbose_name='Datos Nuevos')),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Modificó')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='black_invoices.ventas', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Historial de Venta',
                'verbose_name_plural': 'Historial de Ventas',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleGanancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Cantidad Vendida')),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, help_text='Precio al que se vendió el producto', max_digits=10, verbose_name='Precio de Venta Unitario')),
                ('precio_compra_unitario', models.DecimalField(decimal_places=2, help_text='Precio de compra del producto al momento de la venta', max_digits=10, verbose_name='Precio de Compra Unitario')),
                ('ganancia_unitaria', models.DecimalField(decimal_places=2, help_text='Ganancia por unidad (precio_venta - precio_compra)', max_digits=10, verbose_name='Ganancia Unitaria')),
                ('ganancia_total', models.DecimalField(decimal_places=2, help_text='Ganancia total de esta línea (ganancia_unitaria * cantidad)', max_digits=12, verbose_name='Ganancia Total')),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de ganancia sobre el costo', max_digits=5, verbose_name='Margen de Ganancia %')),
                ('fecha_venta', models.DateTimeField(help_text='Fecha cuando se realizó la venta', verbose_name='Fecha de Venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='black_invoices.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ganancia', to='black_invoices.ventas', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Ganancia',
                'verbose_name_plural': 'Detalles de Ganancia',
                'ordering': ['-fecha_venta'],
                'indexes': [models.Index(fields=['fecha_venta'], name='black_invoi_fecha_v_db638b_idx'), models.Index(fields=['producto'], name='black_invoi_product_db3c23_idx'), models.Index(fields=['venta'], name='black_invoi_venta_i_b7e32b_idx')],
            },
        ),
    ]
